<?php
echo $this->doctype('XHTML1_STRICT');?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?= $this->headTitle($this->translate('administration'));?>
<?= $this->headMeta()->appendName('keywords', 'cms system')
->appendName('Content-Type', 'text/html; charset=utf-8')
->appendName('robots', 'all')
->appendName('revisit-after', '2 days')
->appendName('Pragma', 'cache');
?>
<?= $this->headLink()->appendStylesheet($this->baseUrl.'/css/common.css')
->appendStylesheet($this->baseUrl.'/css/admin/admin.css');
$this->dojo()->setLocalPath($this->baseUrl.'/dojo/dojo/dojo.js')
->addStyleSheetModule('dijit.themes.nihilo')
->addLayer($this->baseUrl.'/dojo/dojo/dojo-ui.js');
echo $this->dojo();
Zend_Dojo_View_Helper_Dojo::setUseProgrammatic();
?>

<script type="text/javascript">
var baseUrl = '<?= $this->escape($this->baseUrl); ?>';
var defaultAjaxTimeout = 800;
</script>
</head>
<style type="text/css">
#messageBox{
	width: 250px;
	margin:25% auto auto auto;
}
</style>
<body class="nihilo">
<div id="loadingJSResources" style="display: none;">
<h1><span class="icon"></span> <?= $this->translate('loadingJavascriptResources')?></h1>
</div>
<script type="text/javascript"> document.getElementById('loadingJSResources').style.display=''; </script>
<div id="extraDiv1"><span></span></div>
<div id="extraDiv2"><span></span></div>
<div id="container">
<div id="extraDiv3"><span></span>
<?= $this->partial('messaging.phtml',Zend_Controller_Action_HelperBroker::getStaticHelper('Messages')->getMessages()) ?>
</div>
<div id="extraDiv4" class="loginLogo"><span></span></div>
<!-- container -->
<?= $this->signInForm; ?>
<!-- container --></div>
<div id="extraDiv5"><span></span></div>
<?= $this->headScript()
->prependFile($this->baseUrl.'/js/admin/common.js')
?>
</body>
</html>
<?
$this->headScript()->appendFile($this->baseUrl.'/js/admin/index/log-in.js');
?>